#!/usr/bin/env python

# Generate vectors.S the trap/interrupt entry points.
# There has to be one entry point per interrupt number
# since otherwise there's no way for trap() to discover
# the interrupt number

print "# generated by vectors.py - do not edit"
print "# handlers"
print ".globl alltraps"

for i in range(0, 256):
    print ".globl vector%d" % (i)
    print "vector%d:" % (i)
    if not (i == 8 or (i >= 10 and i <= 14) or i == 17):
        print "  pushl $0"
    print "  pushl $%d" % (i)
    print "  jmp alltraps"

print "\n # vector table"
print ".data"
print ".globl vectors"
print "vectors:"
for i in range(0, 256):
    print "  .long vector%d" % (i)

# sample output:
#   # handlers
#   .globl alltraps
#   .globl vector0
#   vector0:
#     pushl $0
#     pushl $0
#     jmp alltraps
#   ...
#   
#   # vector table
#   .data
#   .globl vectors
#   vectors:
#     .long vector0
#     .long vector1
#     .long vector2
#   ...
